CREATE TABLE `book` (
  `book_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '图书ID',
  `isbn` varchar(20) NOT NULL COMMENT 'ISBN号',
  `title` varchar(200) NOT NULL COMMENT '书名',
  `author` varchar(100) NOT NULL COMMENT '作者',
  `publisher` varchar(100) COMMENT '出版社',
  `publish_date` date COMMENT '出版日期',
  `category` varchar(50) COMMENT '分类',
  `price` decimal(10,2) COMMENT '价格',
  `total_copies` int(11) DEFAULT 1 COMMENT '总册数',
  `available_copies` int(11) DEFAULT 1 COMMENT '可借册数',
  `location` varchar(100) COMMENT '馆藏位置',
  `description` text COMMENT '图书描述',
  `cover_image` varchar(255) COMMENT '封面图片',
  `keywords` varchar(200) COMMENT '关键词',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`book_id`),
  UNIQUE KEY `uk_isbn` (`isbn`),
  KEY `idx_title` (`title`),
  KEY `idx_author` (`author`),
  KEY `idx_category` (`category`),
  KEY `idx_keywords` (`keywords`),
  KEY `idx_publisher` (`publisher`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='图书表';